#!/usr/bin/env python3
"""
Migration Generator - Creates migration scripts between skill versions
"""

import os
import sys
import difflib
from pathlib import Path
from datetime import datetime

class MigrationGenerator:
    def __init__(self, skill_name, old_version, new_version, source_dir):
        self.skill_name = skill_name
        self.old_version = old_version
        self.new_version = new_version
        self.source_dir = Path(source_dir)
        self.skill_dir = self.source_dir / ".claude" / "skills" / skill_name

    def analyze_changes(self):
        """Analyze what changed between versions"""
        changes = {
            "added": [],
            "removed": [],
            "modified": [],
            "renamed": []
        }

        # Check SKILL.md
        skill_md = self.skill_dir / "SKILL.md"
        if skill_md.exists():
            changes["modified"].append("SKILL.md")

        # Check scripts
        scripts_dir = self.skill_dir / "scripts"
        if scripts_dir.exists():
            for script in scripts_dir.iterdir():
                changes["modified"].append(f"scripts/{script.name}")

        # Check references
        refs_dir = self.skill_dir / "references"
        if refs_dir.exists():
            for ref in refs_dir.iterdir():
                changes["modified"].append(f"references/{ref.name}")

        return changes

    def generate_migration_steps(self, changes):
        """Generate specific migration steps"""
        steps = []

        steps.append("# Migration Steps")
        steps.append("")
        steps.append(f"## {self.skill_name} {self.old_version} → {self.new_version}")
        steps.append(f"Generated: {datetime.now().isoformat()}")
        steps.append("")

        if changes["modified"]:
            steps.append("### Modified Files")
            for file in changes["modified"]:
                steps.append(f"- [ ] Update `{file}`")
            steps.append("")

        if changes["added"]:
            steps.append("### New Files")
            for file in changes["added"]:
                steps.append(f"- [ ] Create `{file}`")
            steps.append("")

        if changes["removed"]:
            steps.append("### Removed Files")
            for file in changes["removed"]:
                steps.append(f"- [ ] Delete `{file}`")
            steps.append("")

        steps.append("### Breaking Changes")
        steps.append("- [ ] Document any breaking changes")
        steps.append("- [ ] Update user documentation")
        steps.append("")

        steps.append("### Testing")
        steps.append("- [ ] Test skill triggers")
        steps.append("- [ ] Validate all workflows")
        steps.append("- [ ] Check resource loading")
        steps.append("")

        return "\n".join(steps)

    def create_migration_package(self, changelog):
        """Create complete migration package"""
        migration_dir = self.skill_dir / "migrations"
        migration_dir.mkdir(exist_ok=True)

        # Analyze changes
        changes = self.analyze_changes()

        # Generate migration steps
        steps = self.generate_migration_steps(changes)

        # Write migration guide
        guide_path = migration_dir / f"migration-{self.old_version}-to-{self.new_version}.md"
        guide_content = f"""# Migration Guide

## Overview
**Skill:** {self.skill_name}
**From:** v{self.old_version}
**To:** v{self.new_version}
**Date:** {datetime.now().strftime('%Y-%m-%d')}

## Changelog
{changelog}

## Changes Summary
{steps}

## Automated Migration
Run: `./migrate-{self.old_version}-to-{self.new_version}.sh`

## Manual Steps Required
{steps}

## Verification
After migration, verify:
1. Skill triggers correctly
2. All resources load
3. No errors in console
4. Workflows complete successfully

## Rollback
If issues occur, run: `./rollback-{self.new_version}-to-{self.old_version}.sh`

---

*Generated by meta-component-updater*